# Generated by Django 4.1.7 on 2023-06-13 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PRODUCTManager', '0001_initial'),
        ('SALESManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='REFUNDREQUESTList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=225)),
                ('amount', models.CharField(max_length=225)),
                ('is_request', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.CharField(max_length=225)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SALESManager.productorderlist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRODUCTManager.productlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
