# Generated by Django 4.1.7 on 2023-04-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialCatList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('is_draft', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('destination', models.CharField(blank=True, default='Student', max_length=200)),
                ('ratting', models.IntegerField(default=5)),
                ('img', models.ImageField(blank=True, default=None, max_length=200, null=True, upload_to='Testimonial/IMG/')),
                ('description', models.TextField(max_length=6000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
