# Generated by Django 4.1.7 on 2023-04-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='AboutUS', max_length=6500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CookiesPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='Cookies Policy', max_length=6500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CopyrightPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='CopyrightPolicy', max_length=6500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disclaimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='Disclaimer', max_length=6500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HowitWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='HowitWorks', max_length=6500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HowToShopOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='How to Shop Online', max_length=6500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='Maintenance', max_length=6500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurFabrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='Our Fabrics', max_length=6500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurGarmentQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='Our Garment Quality', max_length=6500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfectFitGuarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', max_length=6500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='PrivacyPolicy', max_length=6500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PROJECTInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='AakritiCMS', max_length=255, null=True)),
                ('title', models.CharField(blank=True, default='CMS Develop By Mr Das : Ramesh Kuamr Das', max_length=255, null=True)),
                ('baseURL', models.CharField(blank=True, default='http://127.0.0.1:8000', max_length=255, null=True)),
                ('mail', models.EmailField(blank=True, default='das82916@gmail.com', max_length=255, null=True)),
                ('contact', models.CharField(blank=True, default='7322057677', max_length=255, null=True)),
                ('address', models.CharField(blank=True, default='Siraha-21 Laminiya Siraha Prov. No 2 ( NEPAL ) ', max_length=255, null=True)),
                ('SECRET_KEY', models.TextField(blank=True, default='django-insecure-ps(#7dz8ul@wc2^17te7x904fb2zsqka1@tic84rgaa%o62i7o', max_length=6500, null=True)),
                ('DEBUG', models.BooleanField(default=True)),
                ('ALLOWED_HOSTS', models.TextField(blank=True, default='*', max_length=6500, null=True)),
                ('description', models.TextField(blank=True, default='No More Description', max_length=6500, null=True)),
                ('headerLogo', models.ImageField(max_length=200, upload_to='PROJECT/Logo')),
                ('footerLogo', models.ImageField(max_length=200, upload_to='PROJECT/Logo')),
                ('favicon', models.ImageField(max_length=200, upload_to='PROJECT/Logo')),
                ('EMAIL_HOST', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('EMAIL_HOST_USER', models.CharField(default='das82916@gmail.com', max_length=255)),
                ('EMAIL_HOST_PASSWORD', models.CharField(default='rdnrwyrubxutgbgu', max_length=255)),
                ('EMAIL_PORT', models.IntegerField(default=587)),
                ('EMAIL_USE_TLS', models.BooleanField(default=True)),
                ('EMAIL_HOST_NO_REPLY', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('EMAIL_HOST_USER_NO_REPLY', models.CharField(default='das82916@gmail.com', max_length=255)),
                ('EMAIL_HOST_PASSWORD_NO_REPLY', models.CharField(default='rdnrwyrubxutgbgu', max_length=255)),
                ('EMAIL_PORT_NO_REPLY', models.IntegerField(default=587)),
                ('EMAIL_USE_TLS_NO_REPLY', models.BooleanField(default=True)),
                ('RAZORPAY_PAY_ACTIVE', models.BooleanField(default=False)),
                ('RAZORPAY_API_KEY', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('RAZORPAY_API_SECRET', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('PAYPAL_PAY_ACTIVE', models.BooleanField(default=False)),
                ('PAYPAL_API_KEY', models.CharField(default='AQq4VESxR1hUfAGBVSuD3IXH5TF0LpF1Ixm9Mr5CesX5Gydce3qna5nC01Z0hPkgr_fYgmHu5BZF3UOo', max_length=255)),
                ('PAYPAL_API_SECRET', models.CharField(default='', max_length=255)),
                ('facebook', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('youtube', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pintrest', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('support_email', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('support_contact', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('support_address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('PrivacyPolicy', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('TermsCondition', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Security', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Disclaimer', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('CopyrightPolicy', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('AboutUS', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ContactUS', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('google_analytics', models.TextField(blank=True, default='Past Google Analytics Code ', max_length=6500, null=True)),
                ('google_console', models.TextField(blank=True, default='Past Google Console Code ', max_length=6500, null=True)),
                ('meta_title', models.TextField(blank=True, default='Meta title ', max_length=6500, null=True)),
                ('meta_keywords', models.TextField(blank=True, default='Meta keywords', max_length=6500, null=True)),
                ('meta_description', models.TextField(blank=True, default='Meta description', max_length=6500, null=True)),
                ('keing_tag', models.TextField(blank=True, default='Meta ', max_length=6500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RCRPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='RCRPolicy', max_length=6500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='Security', max_length=6500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='TermCondition', max_length=6500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weddings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', max_length=6500, null=True)),
            ],
        ),
    ]
