# Generated by Django 4.1.7 on 2023-06-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtraSettings', '0003_delete_aboutus_delete_cookiespolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinformation',
            name='ChatGTP_API_KEY',
            field=models.TextField(blank=True, default='', max_length=6500, null=True),
        ),
    ]
