# Generated by Django 4.1.7 on 2023-06-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtraSettings', '0004_projectinformation_chatgtp_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinformation',
            name='ChatGTP_API_KEY',
            field=models.TextField(blank=True, default='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', max_length=6500, null=True),
        ),
        migrations.AlterField(
            model_name='projectinformation',
            name='google_analytics',
            field=models.TextField(blank=True, default='', max_length=6500, null=True),
        ),
        migrations.AlterField(
            model_name='projectinformation',
            name='google_console',
            field=models.TextField(blank=True, default='', max_length=6500, null=True),
        ),
    ]
