# Generated by Django 4.1.7 on 2023-06-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtraSettings', '0006_rename_google_console_projectinformation_google_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinformation',
            name='google_client_id',
            field=models.TextField(blank=True, default='', max_length=6500, null=True),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='google_developer_token',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='google_login_customer_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='google_refresh_token',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='google_secret_key',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='google_use_proto_plus',
            field=models.BooleanField(default=True),
        ),
    ]
