# Generated by Django 4.1.7 on 2023-06-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtraSettings', '0008_alter_projectinformation_google_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinformation',
            name='vimeo',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
