# Generated by Django 3.2.19 on 2023-05-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BULKEMAILManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='contact',
            field=models.CharField(default='', max_length=20),
        ),
    ]
