# Generated by Django 4.1.7 on 2023-05-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BULKEMAILManager', '0003_auto_20230504_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillist',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailtemplatelist',
            name='description',
            field=models.TextField(max_length=6500),
        ),
    ]
