# Generated by Django 4.2.2 on 2023-08-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='more',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='scode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='scolony',
            new_name='colony',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='scity',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='scountry',
            new_name='house_no',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='slandmark',
            new_name='landmark',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shouse_no',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='sstate',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='fname',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='lname',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='billingADDRESS',
        ),
    ]
