# Generated by Django 4.2.2 on 2023-08-11 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0002_rename_more_shippingaddress_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='emailOTP',
        ),
        migrations.DeleteModel(
            name='mobileOTP',
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SHIPPINGADDRESSList', to=settings.AUTH_USER_MODEL),
        ),
    ]
