# Generated by Django 4.1.7 on 2023-04-21 06:41

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('token', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, default='+917322057677', max_length=20, null=True)),
                ('username', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='email', unique=True)),
                ('password', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, default='Accounts/DefaultIMG/profile.png', max_length=200, null=True, upload_to='Accounts/adminOZYMed/profileIMG/')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_accountant', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(default=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_account_completed', models.BooleanField(default=False)),
                ('is_agree', models.BooleanField(default=True)),
                ('is_reference', models.BooleanField(default=False)),
                ('reference', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('is_login', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('is_access', models.BooleanField(default=False)),
                ('is_access_days', models.IntegerField(default=0)),
                ('AttemptCount', models.IntegerField(default=1)),
                ('login_block', models.BooleanField(default=True)),
                ('designation', models.CharField(default='Developer', max_length=100)),
                ('gender', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('dbirth', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('role', models.IntegerField(blank=True, default=0)),
                ('pancard', models.CharField(blank=True, default='', max_length=200)),
                ('aadharcard', models.CharField(blank=True, default='', max_length=200)),
                ('intro', models.TextField(blank=True, default='', max_length=1000)),
                ('experience', models.TextField(blank=True, default='', max_length=1000)),
                ('education', models.TextField(blank=True, default='B-Tech in Computer Science from Geeta University', max_length=1000)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('address1', models.CharField(blank=True, default='', max_length=200)),
                ('pincode', models.IntegerField(default=110058)),
                ('state', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=200)),
                ('country', models.CharField(blank=True, default='', max_length=200)),
                ('skills', models.CharField(blank=True, default='', max_length=200)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.CharField(blank=True, default='', max_length=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(max_length=6000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AdminActivity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
