# Generated by Django 4.1.7 on 2023-04-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminAuthentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminregistration',
            name='fname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adminregistration',
            name='lname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
