# Generated by Django 4.1.7 on 2023-04-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminAuthentication', '0002_alter_adminregistration_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminregistration',
            name='aadharcard',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adminregistration',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adminregistration',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adminregistration',
            name='city',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adminregistration',
            name='country',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adminregistration',
            name='education',
            field=models.TextField(blank=True, default='B-Tech in Computer Science from Geeta University', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='adminregistration',
            name='experience',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='adminregistration',
            name='intro',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='adminregistration',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adminregistration',
            name='pancard',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adminregistration',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adminregistration',
            name='state',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
