# Generated by Django 4.1.7 on 2023-05-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminAuthentication', '0003_alter_adminregistration_aadharcard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminregistration',
            name='img',
            field=models.ImageField(blank=True, default='Accounts/DefaultIMG/profile.png', max_length=200, null=True, upload_to='Accounts/AakritiMART/profileIMG/'),
        ),
    ]
