# Generated by Django 4.1.7 on 2023-06-14 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BLOGManager', '0002_replychildblogcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglist',
            name='mainCat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BLOGMainCat', to='BLOGManager.blogmaincat'),
        ),
    ]
