# Generated by Django 4.1.7 on 2023-06-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATEGORYManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='is_header',
            field=models.BooleanField(default=False),
        ),
    ]
