# Generated by Django 4.1.7 on 2023-06-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTManager', '0003_alter_productlist_hsncode_alter_productlist_cgst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlist',
            name='end_date',
            field=models.CharField(blank=True, default='15 Jun, 2023', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='offerlist',
            name='start_date',
            field=models.CharField(blank=True, default='15 Jun, 2023', max_length=15, null=True),
        ),
    ]
