# Generated by Django 4.1.7 on 2023-06-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTManager', '0006_alter_offerlist_end_date_alter_offerlist_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlist',
            name='end_date',
            field=models.CharField(blank=True, default='20 Jun, 2023', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='offerlist',
            name='start_date',
            field=models.CharField(blank=True, default='20 Jun, 2023', max_length=15, null=True),
        ),
    ]
