# Generated by Django 4.1.7 on 2023-06-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTManager', '0007_alter_offerlist_end_date_alter_offerlist_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlist',
            old_name='is_Arrivals',
            new_name='is_arrivals',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='is_Best',
            new_name='is_deal',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='is_Flash',
            new_name='is_discount',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='is_best_offer',
            new_name='is_featured',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='is_today',
            new_name='is_selling',
        ),
        migrations.RemoveField(
            model_name='productlist',
            name='is_top_selling',
        ),
        migrations.AlterField(
            model_name='offerlist',
            name='end_date',
            field=models.CharField(blank=True, default='23 Jun, 2023', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='offerlist',
            name='start_date',
            field=models.CharField(blank=True, default='23 Jun, 2023', max_length=15, null=True),
        ),
    ]
