# Generated by Django 4.2.2 on 2023-06-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTManager', '0010_productlist_is_trending_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlist',
            name='end_date',
            field=models.CharField(blank=True, default='24 Jun, 2023', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='offerlist',
            name='start_date',
            field=models.CharField(blank=True, default='24 Jun, 2023', max_length=15, null=True),
        ),
    ]
