# Generated by Django 4.2.2 on 2023-06-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTManager', '0012_alter_offerlist_end_date_alter_offerlist_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
