# Generated by Django 4.2.2 on 2023-06-25 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CATEGORYManager', '0002_maincategory_is_header'),
        ('PRODUCTManager', '0013_alter_productlist_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='SubSubCat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CATEGORYManager.subsubcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productlist',
            name='mainCat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CATEGORYManager.maincategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productlist',
            name='subCat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CATEGORYManager.subcategory'),
            preserve_default=False,
        ),
    ]
