# Generated by Django 4.2.2 on 2023-06-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTManager', '0014_alter_productlist_subsubcat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlist',
            name='end_date',
            field=models.CharField(blank=True, default='01 Jul, 2023', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='offerlist',
            name='start_date',
            field=models.CharField(blank=True, default='01 Jul, 2023', max_length=15, null=True),
        ),
    ]
