# Generated by Django 4.2.2 on 2023-08-01 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CommonModules', '0023_alter_colorlist_date_alter_regionlist_date_and_more'),
        ('PRODUCTManager', '0015_alter_offerlist_end_date_alter_offerlist_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributeproductlist',
            name='size',
        ),
        migrations.AddField(
            model_name='productlist',
            name='attributes',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productlist',
            name='is_quantity',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attributeproductlist',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CommonModules.colorlist'),
        ),
        migrations.AlterField(
            model_name='offerlist',
            name='end_date',
            field=models.CharField(blank=True, default='01 Aug, 2023', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='offerlist',
            name='start_date',
            field=models.CharField(blank=True, default='01 Aug, 2023', max_length=15, null=True),
        ),
    ]
