# Generated by Django 4.2.2 on 2023-08-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTManager', '0016_remove_attributeproductlist_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlist',
            old_name='is_quantity',
            new_name='product_type',
        ),
        migrations.AlterField(
            model_name='offerlist',
            name='end_date',
            field=models.CharField(blank=True, default='02 Aug, 2023', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='offerlist',
            name='start_date',
            field=models.CharField(blank=True, default='02 Aug, 2023', max_length=15, null=True),
        ),
    ]
