# Generated by Django 4.2.2 on 2023-08-02 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTManager', '0017_rename_is_quantity_productlist_product_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIMILARPRODUCTSList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrp', models.FloatField(default=0.0)),
                ('sp', models.FloatField(default=0.0)),
                ('attributes', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PRODUCTManager.productlist')),
            ],
        ),
    ]
