# Generated by Django 4.2.2 on 2023-08-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTManager', '0018_similarproductslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmycart',
            name='attribute',
            field=models.CharField(blank=True, default=1, max_length=120, null=True),
        ),
    ]
