# Generated by Django 4.2.2 on 2023-08-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTManager', '0019_productmycart_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmycart',
            name='mrp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productmycart',
            name='sp',
            field=models.FloatField(default=0.0),
        ),
    ]
