# Generated by Django 4.2.2 on 2023-08-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTManager', '0021_alter_offerlist_end_date_alter_offerlist_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlist',
            name='end_date',
            field=models.CharField(blank=True, default='11 Aug, 2023', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='offerlist',
            name='start_date',
            field=models.CharField(blank=True, default='11 Aug, 2023', max_length=15, null=True),
        ),
    ]
