# Generated by Django 4.1.7 on 2023-06-13 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SALESManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCRREQUESTList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_return', models.BooleanField(default=False)),
                ('is_cancel', models.BooleanField(default=False)),
                ('is_replacement', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RCRList', to='SALESManager.productorderlist')),
            ],
        ),
    ]
