# Generated by Django 4.1.7 on 2023-04-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COLORList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('date', models.CharField(blank=True, default='21, April - 2023', max_length=15, null=True)),
                ('last_update', models.CharField(blank=True, default='', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='REGIONList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pcode', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('date', models.CharField(blank=True, default='21, April - 2023', max_length=15, null=True)),
                ('last_update', models.CharField(blank=True, default='', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SHIPPINGList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('kg_range', models.CharField(max_length=255)),
                ('local', models.FloatField(default=0)),
                ('regional', models.FloatField(default=0)),
                ('national', models.FloatField(default=0)),
                ('special', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('date', models.CharField(blank=True, default='21, April - 2023', max_length=15, null=True)),
                ('last_update', models.CharField(blank=True, default='', max_length=15, null=True)),
            ],
        ),
    ]
