# Generated by Django 4.1.7 on 2023-04-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonModules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorlist',
            name='date',
            field=models.CharField(blank=True, default='24, April - 2023', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='regionlist',
            name='date',
            field=models.CharField(blank=True, default='24, April - 2023', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='shippinglist',
            name='date',
            field=models.CharField(blank=True, default='24, April - 2023', max_length=15, null=True),
        ),
    ]
