# Generated by Django 4.1.7 on 2023-04-21 06:42

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SECTIONList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(max_length=200, upload_to='INDUSTRYList/Items')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True)),
                ('redirect_to', models.CharField(blank=True, default='javascript:void(0);', max_length=225, null=True)),
                ('is_header', models.BooleanField(default=False)),
                ('is_footer', models.BooleanField(default=False)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PAGEList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, max_length=255, populate_from='name', unique=True)),
                ('is_url', models.BooleanField(default=False)),
                ('redirect_to', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='Description is Required', max_length=6000)),
                ('meta_title', models.CharField(default='', max_length=255)),
                ('meta_keywords', models.TextField(default='', max_length=6500)),
                ('meta_description', models.CharField(default='', max_length=255)),
                ('views', models.IntegerField(default=0)),
                ('is_draft', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CMSManager.sectionlist')),
            ],
        ),
    ]
