# Generated by Django 4.1.7 on 2023-04-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMSManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionlist',
            old_name='is_mobile',
            new_name='is_menu',
        ),
    ]
