# Generated by Django 4.1.7 on 2023-04-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMSManager', '0002_rename_is_mobile_sectionlist_is_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionlist',
            name='logo',
            field=models.TextField(blank=True, default='', max_length=6000, null=True),
        ),
    ]
