# Generated by Django 4.1.7 on 2023-04-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMSManager', '0003_sectionlist_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionlist',
            name='logo',
            field=models.TextField(blank=True, default='logo', max_length=6000, null=True),
        ),
    ]
