# Generated by Django 4.1.7 on 2023-06-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTManager', '0004_alter_offerlist_end_date_alter_offerlist_start_date'),
        ('CMSManager', '0005_alter_sectionlist_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelist',
            name='product',
            field=models.ManyToManyField(related_name='CMSProductList', to='PRODUCTManager.productlist'),
        ),
    ]
