# Generated by Django 4.2.2 on 2023-08-11 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PRODUCTManager', '0022_alter_offerlist_end_date_alter_offerlist_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.CharField(blank=True, max_length=225, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=225, null=True)),
                ('is_agree', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp', models.IntegerField()),
                ('author', models.CharField(blank=True, default='Super Admin', max_length=225, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.CharField(blank=True, default='11, August - 2023', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=225, null=True)),
                ('pay_status', models.CharField(blank=True, default='', max_length=225, null=True)),
                ('tno', models.CharField(blank=True, max_length=225, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRODUCTManager.productlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=225)),
                ('invoice', models.CharField(max_length=225)),
                ('amount', models.FloatField()),
                ('gst', models.FloatField(default=1)),
                ('shipping', models.FloatField(default=1)),
                ('discount', models.FloatField()),
                ('subtotal', models.FloatField(default=1)),
                ('total', models.FloatField(default=1)),
                ('qty', models.IntegerField(default=1)),
                ('color', models.CharField(max_length=225)),
                ('attribute', models.CharField(max_length=225)),
                ('fname', models.CharField(default='', max_length=225)),
                ('lname', models.CharField(default='', max_length=225)),
                ('email', models.CharField(default='', max_length=225)),
                ('contact', models.CharField(default='', max_length=225)),
                ('code', models.IntegerField(blank=True, default='', null=True)),
                ('house_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('landmark', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('colony', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('is_cancel', models.BooleanField(default=False)),
                ('is_shipped', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('payMethod', models.CharField(default='', max_length=225)),
                ('is_payment', models.BooleanField(default=False)),
                ('is_otp', models.IntegerField(default=0)),
                ('track', models.CharField(default='', max_length=225)),
                ('order_id', models.CharField(blank=True, max_length=225, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=225, null=True)),
                ('signature', models.CharField(blank=True, max_length=225, null=True)),
                ('jsonOBJ', models.TextField(default='', max_length=5000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('on_delivered', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRODUCTManager.productlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
