# Generated by Django 4.2.2 on 2023-08-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SALESManager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentGatewayList',
        ),
        migrations.AlterField(
            model_name='productorderlist',
            name='contact',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
