# Generated by Django 4.1.7 on 2023-06-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SALESManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgatewaylist',
            name='last_update',
            field=models.CharField(blank=True, default='14, June - 2023', max_length=20, null=True),
        ),
    ]
