# Generated by Django 4.1.7 on 2023-06-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SALESManager', '0002_alter_paymentgatewaylist_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgatewaylist',
            name='last_update',
            field=models.CharField(blank=True, default='15, June - 2023', max_length=20, null=True),
        ),
    ]
