# Generated by Django 4.1.7 on 2023-06-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SALESManager', '0004_alter_paymentgatewaylist_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgatewaylist',
            name='last_update',
            field=models.CharField(blank=True, default='19, June - 2023', max_length=20, null=True),
        ),
    ]
