# Generated by Django 4.2.2 on 2023-06-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SALESManager', '0007_alter_paymentgatewaylist_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgatewaylist',
            name='last_update',
            field=models.CharField(blank=True, default='24, June - 2023', max_length=20, null=True),
        ),
    ]
